/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz.core;

import depro.dao.HibernateDAOImpl;
import depro.dao.PluDAOImpl;
import depro.dao.PrecioDAOImpl;
import depro.dao.UsuarioDAOImpl;
import depro.dao.VentaDAOImpl;
import depro.dao.PuntoVentaDAOImpl;
import depro.dao.DAOManager;
import depro.dao.MovimientoDAOImpl;
import depro.gestorArchivo.GestorManager;
import depro.modelo.Movimiento;
import depro.modelo.Plu;
import depro.modelo.Precio;
import depro.modelo.PuntoVenta;
import depro.modelo.Usuario;
import depro.modelo.Venta;
import depro.util.CargaProperties;
import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.List;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author jhunior
 */
public class InterfazPrincipal extends javax.swing.JFrame {

    static DAOManager dAOManager;
    static GestorManager gestorManager;
    private static int tiendaUsuario;
    private static String tipoUsuario = "No hay usuario conectado";
    private static int stateConnection = 0;
    private static String directorioUsuario;
    private CargaProperties lectorProperties;
    private String nombreTienda;

    /**
     * Creates new form InterfazPrincipal
     */
    public InterfazPrincipal() throws Exception {
        dAOManager = new DAOManager();
        gestorManager = new GestorManager();
        gestorManager.setDAOManager(dAOManager);
        directorioUsuario = "C:\\";
        lectorProperties = new CargaProperties();
        tiendaUsuario = lectorProperties.obtenerEscala();
        nombreTienda = lectorProperties.obtenerNombreTienda();
        initComponents();
        llenarComboBoxUsuario();
        setTitle(nombreTienda);
    }

    /**
     * *
     * Método para realizar el llenado del comboBox que muestra el nombre de
     * cada usuario registrado en el sistema
     */
    private void llenarComboBoxUsuario() {
        try {
            throw new Exception();
//            List<String> nombresUsuario = dAOManager.getUsuarioDAOImpl().listarNombreUsuarios();
//            DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBoxUsuarios.getModel();
//            model.removeAllElements();
//            model.addElement("Superusuario");
//            for (String nombreUsuario : nombresUsuario) {
//                model.addElement(nombreUsuario);
//            }
//            jComboBoxUsuarios.setSelectedIndex(-1);
        } catch (Exception e) {
            DefaultComboBoxModel model = (DefaultComboBoxModel) jComboBoxUsuarios.getModel();
            model.removeAllElements();
            model.addElement("Superusuario");
            jComboBoxUsuarios.setSelectedIndex(-1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventanaInicio = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        btnAcpetar = new javax.swing.JButton();
        jComboBoxUsuarios = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        menuArchivo2 = new javax.swing.JMenu();
        menuSalir2 = new javax.swing.JMenuItem();
        menuAyuda2 = new javax.swing.JMenu();
        itemAyuda2 = new javax.swing.JMenuItem();
        jFileChooser1 = new javax.swing.JFileChooser();
        jFileChooser2 = new javax.swing.JFileChooser();
        jMenu1 = new javax.swing.JMenu();
        jDialogCargaCrearReporte = new javax.swing.JDialog();
        jLabel22 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jDialogCapturaPlu = new javax.swing.JDialog();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldRutaPlu = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jDialogVerMovimiento = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableMovimiento = new javax.swing.JTable();
        jDialogVerTiendas = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTienda = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jDialogVerPlus = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePlu = new javax.swing.JTable();
        jDialogVerVentas = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableVenta = new javax.swing.JTable();
        jDialogVerPrecios = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablePrecio = new javax.swing.JTable();
        jButton9 = new javax.swing.JButton();
        jDialogCrearUsuarios = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDialogCrearTiendas = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButtonCancelarCrearTienda = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jPanelInformacionUsuario = new javax.swing.JPanel();
        jLabelTipoUsuario = new javax.swing.JLabel();
        jLabelTienda = new javax.swing.JLabel();
        jLabelNombreTienda = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuSesion = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        menuCrearUsuario = new javax.swing.JMenuItem();
        jMenuItemRegistrarPuntoVenta = new javax.swing.JMenuItem();
        menuHerramientas = new javax.swing.JMenu();
        jMenuImportar = new javax.swing.JMenu();
        jMenuItemCapturarPlu = new javax.swing.JMenuItem();
        jMenuConsolidar = new javax.swing.JMenu();
        jMenuItemConsolidar = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuVista = new javax.swing.JMenu();
        jMenuItemVerTiendas = new javax.swing.JMenuItem();
        jMenuItemVerPlu = new javax.swing.JMenuItem();
        jMenuItemVerVentas = new javax.swing.JMenuItem();
        jMenuItemVerPrecios = new javax.swing.JMenuItem();
        jMenuItemVerMovimiento = new javax.swing.JMenuItem();
        jMenuReporte = new javax.swing.JMenu();
        jMenuItemReportePlu = new javax.swing.JMenuItem();
        jMenuItemReporteFecha = new javax.swing.JMenuItem();
        jMenuItemReporteEscala = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        itemAyuda = new javax.swing.JMenuItem();

        ventanaInicio.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        ventanaInicio.setAlwaysOnTop(true);
        ventanaInicio.setMinimumSize(new java.awt.Dimension(410, 320));
        ventanaInicio.setResizable(false);

        btnAcpetar.setText("Aceptar");
        btnAcpetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcpetarActionPerformed(evt);
            }
        });

        jComboBoxUsuarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxUsuariosItemStateChanged(evt);
            }
        });

        jLabel1.setText("Nombre de usuario");
        jLabel1.setAutoscrolls(true);

        jLabel2.setText("Contraseña");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAcpetar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnAcpetar)
                .addGap(19, 19, 19))
        );

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Crear nuevo usuario");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });

        menuArchivo2.setText("Archivo");

        menuSalir2.setText("Salir");
        menuSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalir2ActionPerformed(evt);
            }
        });
        menuArchivo2.add(menuSalir2);

        jMenuBar3.add(menuArchivo2);

        menuAyuda2.setText("Ayuda");

        itemAyuda2.setText("Ayuda");
        menuAyuda2.add(itemAyuda2);

        jMenuBar3.add(menuAyuda2);

        ventanaInicio.setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout ventanaInicioLayout = new javax.swing.GroupLayout(ventanaInicio.getContentPane());
        ventanaInicio.getContentPane().setLayout(ventanaInicioLayout);
        ventanaInicioLayout.setHorizontalGroup(
            ventanaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ventanaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaInicioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel25)
                        .addGap(36, 36, 36)))
                .addContainerGap())
        );
        ventanaInicioLayout.setVerticalGroup(
            ventanaInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventanaInicioLayout.createSequentialGroup()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jFileChooser1.setCurrentDirectory(new java.io.File("D:\\Proyecto\\Carnes"));

        jFileChooser2.setCurrentDirectory(new java.io.File("C:\\"));
            jFileChooser2.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);

            jMenu1.setText("jMenu1");

            jDialogCargaCrearReporte.setMinimumSize(new java.awt.Dimension(460, 170));

            jLabel22.setText("Creando reporte seleccionado, espere mientras se genera");

            jProgressBar1.setToolTipText("Espere por favor....");
            jProgressBar1.setIndeterminate(true);
            jProgressBar1.setString("Espere por favor....");
            jProgressBar1.setStringPainted(true);

            javax.swing.GroupLayout jDialogCargaCrearReporteLayout = new javax.swing.GroupLayout(jDialogCargaCrearReporte.getContentPane());
            jDialogCargaCrearReporte.getContentPane().setLayout(jDialogCargaCrearReporteLayout);
            jDialogCargaCrearReporteLayout.setHorizontalGroup(
                jDialogCargaCrearReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogCargaCrearReporteLayout.createSequentialGroup()
                    .addGroup(jDialogCargaCrearReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogCargaCrearReporteLayout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(43, 43, 43))
                        .addGroup(jDialogCargaCrearReporteLayout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(31, 31, 31))
            );
            jDialogCargaCrearReporteLayout.setVerticalGroup(
                jDialogCargaCrearReporteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogCargaCrearReporteLayout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(38, Short.MAX_VALUE))
            );

            jDialogCapturaPlu.setMinimumSize(new java.awt.Dimension(410, 220));
            jDialogCapturaPlu.setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

            jButton5.setText("Aceptar");
            jButton5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton5ActionPerformed(evt);
                }
            });

            jButton6.setText("Cancelar");
            jButton6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton6ActionPerformed(evt);
                }
            });

            jLabel13.setText("Captura de Plu");

            jLabel14.setText("Ruta");

            jButton7.setText("Examinar");
            jButton7.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton7ActionPerformed(evt);
                }
            });

            jPanel1.setFocusable(false);
            jPanel1.setName(""); // NOI18N

            jProgressBar2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
            jProgressBar2.setToolTipText("Ejecutando modelos, espere por favor...");
            jProgressBar2.setIndeterminate(true);
            jProgressBar2.setString("Cargando archivo, espere por favor...");
            jProgressBar2.setStringPainted(true);

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            javax.swing.GroupLayout jDialogCapturaPluLayout = new javax.swing.GroupLayout(jDialogCapturaPlu.getContentPane());
            jDialogCapturaPlu.getContentPane().setLayout(jDialogCapturaPluLayout);
            jDialogCapturaPluLayout.setHorizontalGroup(
                jDialogCapturaPluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogCapturaPluLayout.createSequentialGroup()
                    .addGroup(jDialogCapturaPluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogCapturaPluLayout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(jDialogCapturaPluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jDialogCapturaPluLayout.createSequentialGroup()
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextFieldRutaPlu, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton7))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jDialogCapturaPluLayout.createSequentialGroup()
                            .addGap(46, 46, 46)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(45, 45, 45)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(32, Short.MAX_VALUE))
            );
            jDialogCapturaPluLayout.setVerticalGroup(
                jDialogCapturaPluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogCapturaPluLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(28, 28, 28)
                    .addGroup(jDialogCapturaPluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldRutaPlu, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton7))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                    .addGroup(jDialogCapturaPluLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            jDialogVerMovimiento.setMinimumSize(new java.awt.Dimension(760, 170));

            jTableMovimiento.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "# Transaccion", "Plu", "Precio", "Peso (g)", "Costo", "Fecha", "Hora", "# Escala", "Nombre"
                }
            ) {
                boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false, false, false, false
                };

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            jScrollPane5.setViewportView(jTableMovimiento);

            javax.swing.GroupLayout jDialogVerMovimientoLayout = new javax.swing.GroupLayout(jDialogVerMovimiento.getContentPane());
            jDialogVerMovimiento.getContentPane().setLayout(jDialogVerMovimientoLayout);
            jDialogVerMovimientoLayout.setHorizontalGroup(
                jDialogVerMovimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogVerMovimientoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jDialogVerMovimientoLayout.setVerticalGroup(
                jDialogVerMovimientoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogVerMovimientoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addContainerGap())
            );

            jDialogVerTiendas.setMinimumSize(new java.awt.Dimension(560, 250));

            jTableTienda.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Id", "Nombre", "Direccion", "Ciudad", "Telefono", "Celular"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                };
                boolean[] canEdit = new boolean [] {
                    false, true, true, true, true, true
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            jTableTienda.getTableHeader().setReorderingAllowed(false);
            jScrollPane1.setViewportView(jTableTienda);

            jButton8.setText("Guardar cambios");
            jButton8.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton8ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jDialogVerTiendasLayout = new javax.swing.GroupLayout(jDialogVerTiendas.getContentPane());
            jDialogVerTiendas.getContentPane().setLayout(jDialogVerTiendasLayout);
            jDialogVerTiendasLayout.setHorizontalGroup(
                jDialogVerTiendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogVerTiendasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                    .addComponent(jButton8)
                    .addContainerGap())
            );
            jDialogVerTiendasLayout.setVerticalGroup(
                jDialogVerTiendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogVerTiendasLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jButton8)
                    .addContainerGap(207, Short.MAX_VALUE))
                .addGroup(jDialogVerTiendasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addContainerGap())
            );

            jDialogVerPlus.setMinimumSize(new java.awt.Dimension(480, 320));

            jTablePlu.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Id Plu", "Código de barras", "Nombre"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class
                };
                boolean[] canEdit = new boolean [] {
                    false, false, false
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            jTablePlu.getTableHeader().setReorderingAllowed(false);
            jScrollPane2.setViewportView(jTablePlu);

            javax.swing.GroupLayout jDialogVerPlusLayout = new javax.swing.GroupLayout(jDialogVerPlus.getContentPane());
            jDialogVerPlus.getContentPane().setLayout(jDialogVerPlusLayout);
            jDialogVerPlusLayout.setHorizontalGroup(
                jDialogVerPlusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogVerPlusLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE))
            );
            jDialogVerPlusLayout.setVerticalGroup(
                jDialogVerPlusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogVerPlusLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jDialogVerVentas.setMinimumSize(new java.awt.Dimension(460, 320));

            jTableVenta.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Numero transacción", "Fecha", "Peso (gr)", "Código plu", "Código Tienda"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
                };
                boolean[] canEdit = new boolean [] {
                    false, false, false, false, false
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            jTableVenta.getTableHeader().setReorderingAllowed(false);
            jScrollPane3.setViewportView(jTableVenta);

            javax.swing.GroupLayout jDialogVerVentasLayout = new javax.swing.GroupLayout(jDialogVerVentas.getContentPane());
            jDialogVerVentas.getContentPane().setLayout(jDialogVerVentasLayout);
            jDialogVerVentasLayout.setHorizontalGroup(
                jDialogVerVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogVerVentasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(35, Short.MAX_VALUE))
            );
            jDialogVerVentasLayout.setVerticalGroup(
                jDialogVerVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogVerVentasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE))
            );

            jDialogVerPrecios.setMinimumSize(new java.awt.Dimension(540, 290));

            jTablePrecio.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Código Tienda", "Código Plu", "Precio"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
                };
                boolean[] canEdit = new boolean [] {
                    false, false, true
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
            jTablePrecio.getTableHeader().setReorderingAllowed(false);
            jScrollPane4.setViewportView(jTablePrecio);

            jButton9.setText("Guardar cambios");
            jButton9.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton9ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jDialogVerPreciosLayout = new javax.swing.GroupLayout(jDialogVerPrecios.getContentPane());
            jDialogVerPrecios.getContentPane().setLayout(jDialogVerPreciosLayout);
            jDialogVerPreciosLayout.setHorizontalGroup(
                jDialogVerPreciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogVerPreciosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addGap(19, 19, 19)
                    .addComponent(jButton9)
                    .addContainerGap())
            );
            jDialogVerPreciosLayout.setVerticalGroup(
                jDialogVerPreciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogVerPreciosLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jDialogVerPreciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogVerPreciosLayout.createSequentialGroup()
                            .addComponent(jButton9)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                    .addContainerGap())
            );

            jDialogCrearUsuarios.setMinimumSize(new java.awt.Dimension(280, 400));
            jDialogCrearUsuarios.setResizable(false);

            jLabel3.setText("Nombre");

            jLabel4.setText("Apellido");

            jLabel5.setText("Contraseña");

            jLabel6.setText("Nombre de usuario");

            jLabel7.setText("Confirmar contraseña");

            jLabel8.setText("Tipo de Usuario");

            jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Normal", "Invitado" }));
            jComboBox1.setSelectedIndex(-1);
            jComboBox1.setSelectedItem(null);

            jButton1.setText("Aceptar");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jButton2.setText("Cancelar");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jDialogCrearUsuariosLayout = new javax.swing.GroupLayout(jDialogCrearUsuarios.getContentPane());
            jDialogCrearUsuarios.getContentPane().setLayout(jDialogCrearUsuariosLayout);
            jDialogCrearUsuariosLayout.setHorizontalGroup(
                jDialogCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogCrearUsuariosLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(jDialogCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogCrearUsuariosLayout.createSequentialGroup()
                            .addGroup(jDialogCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jDialogCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addComponent(jTextField2)
                                .addComponent(jTextField4)))
                        .addGroup(jDialogCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jDialogCrearUsuariosLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialogCrearUsuariosLayout.createSequentialGroup()
                                .addGroup(jDialogCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDialogCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordField3)
                                    .addGroup(jDialogCrearUsuariosLayout.createSequentialGroup()
                                        .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addContainerGap(14, Short.MAX_VALUE))
                .addGroup(jDialogCrearUsuariosLayout.createSequentialGroup()
                    .addGap(37, 37, 37)
                    .addComponent(jButton1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2)
                    .addGap(37, 37, 37))
            );
            jDialogCrearUsuariosLayout.setVerticalGroup(
                jDialogCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogCrearUsuariosLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(jDialogCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jDialogCrearUsuariosLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addGroup(jDialogCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField3))
                    .addGap(18, 18, 18)
                    .addGroup(jDialogCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField4))
                    .addGap(18, 18, 18)
                    .addGroup(jDialogCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPasswordField2))
                    .addGap(18, 18, 18)
                    .addGroup(jDialogCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jDialogCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jDialogCrearUsuariosLayout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jComboBox1)))
                    .addGap(18, 18, 18)
                    .addGroup(jDialogCrearUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2)
                        .addComponent(jButton1))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jDialogCrearTiendas.setMinimumSize(new java.awt.Dimension(385, 250));
            jDialogCrearTiendas.setResizable(false);

            jPanel2.setLayout(new java.awt.GridLayout(7, 2));

            jLabel15.setText("Serial");
            jPanel2.add(jLabel15);
            jPanel2.add(jTextField7);

            jLabel16.setText("Nombre");
            jPanel2.add(jLabel16);
            jPanel2.add(jTextField8);

            jLabel17.setText("Dirección");
            jPanel2.add(jLabel17);
            jPanel2.add(jTextField9);

            jLabel18.setText("Ciudad");
            jPanel2.add(jLabel18);
            jPanel2.add(jTextField10);

            jLabel19.setText("Telefono");
            jPanel2.add(jLabel19);
            jPanel2.add(jTextField11);

            jLabel20.setText("Celular");
            jPanel2.add(jLabel20);
            jPanel2.add(jTextField12);

            jLabel21.setText("Ruta por defecto");
            jPanel2.add(jLabel21);
            jPanel2.add(jTextField13);

            jButton10.setText("Aceptar");
            jButton10.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton10ActionPerformed(evt);
                }
            });

            jButtonCancelarCrearTienda.setText("Cancelar");
            jButtonCancelarCrearTienda.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonCancelarCrearTiendaActionPerformed(evt);
                }
            });

            jButton11.setText("...");
            jButton11.setMinimumSize(new java.awt.Dimension(45, 25));
            jButton11.setPreferredSize(new java.awt.Dimension(45, 25));
            jButton11.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton11ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jDialogCrearTiendasLayout = new javax.swing.GroupLayout(jDialogCrearTiendas.getContentPane());
            jDialogCrearTiendas.getContentPane().setLayout(jDialogCrearTiendasLayout);
            jDialogCrearTiendasLayout.setHorizontalGroup(
                jDialogCrearTiendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogCrearTiendasLayout.createSequentialGroup()
                    .addGroup(jDialogCrearTiendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jDialogCrearTiendasLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jDialogCrearTiendasLayout.createSequentialGroup()
                            .addGap(66, 66, 66)
                            .addComponent(jButton10)
                            .addGap(43, 43, 43)
                            .addComponent(jButtonCancelarCrearTienda)))
                    .addContainerGap(13, Short.MAX_VALUE))
            );
            jDialogCrearTiendasLayout.setVerticalGroup(
                jDialogCrearTiendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialogCrearTiendasLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jDialogCrearTiendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jDialogCrearTiendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonCancelarCrearTienda)
                        .addComponent(jButton10))
                    .addContainerGap())
            );

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setTitle("Aplicacion");
            setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
            setExtendedState(6);
            setName("EscritorioGeneral"); // NOI18N

            jPanelInformacionUsuario.setBackground(new java.awt.Color(0, 153, 153));
            jPanelInformacionUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

            javax.swing.GroupLayout jPanelInformacionUsuarioLayout = new javax.swing.GroupLayout(jPanelInformacionUsuario);
            jPanelInformacionUsuario.setLayout(jPanelInformacionUsuarioLayout);
            jPanelInformacionUsuarioLayout.setHorizontalGroup(
                jPanelInformacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelInformacionUsuarioLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelInformacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelInformacionUsuarioLayout.createSequentialGroup()
                            .addGroup(jPanelInformacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabelNombreTienda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelTienda, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                            .addGap(25, 25, 25))
                        .addGroup(jPanelInformacionUsuarioLayout.createSequentialGroup()
                            .addComponent(jLabelTipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                            .addContainerGap())))
            );
            jPanelInformacionUsuarioLayout.setVerticalGroup(
                jPanelInformacionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelInformacionUsuarioLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabelTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabelTienda, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jLabelNombreTienda, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addContainerGap())
            );

            menuArchivo.setText("Archivo");

            menuSesion.setText("Cambiar sesión");
            menuSesion.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    menuSesionActionPerformed(evt);
                }
            });
            menuArchivo.add(menuSesion);

            menuSalir.setText("Salir");
            menuSalir.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    menuSalirActionPerformed(evt);
                }
            });
            menuArchivo.add(menuSalir);

            jMenuBar1.add(menuArchivo);

            menuUsuarios.setText("Registro");

            menuCrearUsuario.setText("Crear Usuario");
            menuCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    menuCrearUsuarioActionPerformed(evt);
                }
            });
            menuUsuarios.add(menuCrearUsuario);

            jMenuItemRegistrarPuntoVenta.setText("Registrar punto de venta");
            jMenuItemRegistrarPuntoVenta.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItemRegistrarPuntoVentaActionPerformed(evt);
                }
            });
            menuUsuarios.add(jMenuItemRegistrarPuntoVenta);

            jMenuBar1.add(menuUsuarios);

            menuHerramientas.setText("Sistema");

            jMenuImportar.setText("Importar");

            jMenuItemCapturarPlu.setText("Capturar PLU");
            jMenuItemCapturarPlu.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItemCapturarPluActionPerformed(evt);
                }
            });
            jMenuImportar.add(jMenuItemCapturarPlu);

            menuHerramientas.add(jMenuImportar);

            jMenuConsolidar.setText("Consolidar");

            jMenuItemConsolidar.setText("Sesión actual");
            jMenuItemConsolidar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItemConsolidarActionPerformed(evt);
                }
            });
            jMenuConsolidar.add(jMenuItemConsolidar);

            jMenuItem3.setText("Todas las sesiones");
            jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItem3ActionPerformed(evt);
                }
            });
            jMenuConsolidar.add(jMenuItem3);

            jMenuItem4.setText("Sesión parametrizable");
            jMenuConsolidar.add(jMenuItem4);

            menuHerramientas.add(jMenuConsolidar);

            jMenuBar1.add(menuHerramientas);

            jMenuVista.setText("Vistas");

            jMenuItemVerTiendas.setText("Ver Puntos de ventas");
            jMenuItemVerTiendas.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItemVerTiendasActionPerformed(evt);
                }
            });
            jMenuVista.add(jMenuItemVerTiendas);

            jMenuItemVerPlu.setText("Ver Plus");
            jMenuItemVerPlu.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItemVerPluActionPerformed(evt);
                }
            });
            jMenuVista.add(jMenuItemVerPlu);

            jMenuItemVerVentas.setText("Ver Ventas");
            jMenuItemVerVentas.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItemVerVentasActionPerformed(evt);
                }
            });
            jMenuVista.add(jMenuItemVerVentas);

            jMenuItemVerPrecios.setText("Ver Precios");
            jMenuItemVerPrecios.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItemVerPreciosActionPerformed(evt);
                }
            });
            jMenuVista.add(jMenuItemVerPrecios);

            jMenuItemVerMovimiento.setText("Ver Movimientos");
            jMenuItemVerMovimiento.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItemVerMovimientoActionPerformed(evt);
                }
            });
            jMenuVista.add(jMenuItemVerMovimiento);

            jMenuBar1.add(jMenuVista);

            jMenuReporte.setText("Reportes");

            jMenuItemReportePlu.setText("Plu");
            jMenuItemReportePlu.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItemReportePluActionPerformed(evt);
                }
            });
            jMenuReporte.add(jMenuItemReportePlu);

            jMenuItemReporteFecha.setText("Fecha");
            jMenuItemReporteFecha.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItemReporteFechaActionPerformed(evt);
                }
            });
            jMenuReporte.add(jMenuItemReporteFecha);

            jMenuItemReporteEscala.setText("Escala");
            jMenuItemReporteEscala.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jMenuItemReporteEscalaActionPerformed(evt);
                }
            });
            jMenuReporte.add(jMenuItemReporteEscala);

            jMenuBar1.add(jMenuReporte);

            menuAyuda.setText("Ayuda");

            itemAyuda.setText("Ayuda");
            menuAyuda.add(itemAyuda);

            jMenuBar1.add(menuAyuda);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 580, Short.MAX_VALUE)
                    .addComponent(jPanelInformacionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 325, Short.MAX_VALUE)
                    .addComponent(jPanelInformacionUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearUsuarioActionPerformed
        List<Integer> tiendas = dAOManager.getPuntoVentaDAOImpl().listaId();
        if (tiendas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay tiendas registradas", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            this.jDialogCrearUsuarios.setVisible(true);
            this.jDialogCrearUsuarios.setLocationRelativeTo(this);
        }
    }//GEN-LAST:event_menuCrearUsuarioActionPerformed

    private void menuSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSesionActionPerformed
        // TODO add your handling code here:
        hacerLogin();
    }//GEN-LAST:event_menuSesionActionPerformed

    private void jMenuItemCapturarPluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCapturarPluActionPerformed
        jTextFieldRutaPlu.setText("");
        jDialogCapturaPlu.setLocationRelativeTo(this);
        jDialogCapturaPlu.setVisible(true);
        jPanel1.setVisible(false);
        jProgressBar2.setVisible(false);
    }//GEN-LAST:event_jMenuItemCapturarPluActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jDialogCrearUsuarios.dispose();
        if (tiendaUsuario == 0) {
            hacerLogin();
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    /**
     * *
     * Evento generado por el boton aceptar de la interfaz de crear un nuevo
     * usuario
     *
     * @param evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Usuario usuario = new Usuario();
        usuario.setNombre(jTextField2.getText());
        usuario.setApellido(jTextField3.getText());
        usuario.setNombreUsuario(jTextField4.getText());
        usuario.setPass(jPasswordField2.getText());
        usuario.setTipoUsuario(jComboBox1.getSelectedItem().toString());
        try {
            UsuarioDAOImpl usuarioDAOImpl = dAOManager.getUsuarioDAOImpl();
            usuarioDAOImpl.iniciarTransaccion();
            Usuario u = usuarioDAOImpl.buscarPorNombreUsuario(usuario.getNombreUsuario());
            if (u == null) {
                char[] pass1 = jPasswordField2.getPassword();
                char[] pass2 = jPasswordField3.getPassword();
                if (Arrays.equals(pass1, pass2)) {
                    usuarioDAOImpl.guardar(usuario);
                    usuarioDAOImpl.commit();
                    usuarioDAOImpl.cerrarSession();
                    jDialogCrearUsuarios.setAlwaysOnTop(false);
                    JOptionPane.showMessageDialog(this, "Usuario guardado satisfactoriamente", "", JOptionPane.PLAIN_MESSAGE);
                    jDialogCrearUsuarios.dispose();
                    if (tiendaUsuario == 0) {
                        hacerLogin();
                    }
                } else {
                    jDialogCrearUsuarios.setAlwaysOnTop(false);
                    JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden", "", JOptionPane.PLAIN_MESSAGE);
                    jDialogCrearUsuarios.setAlwaysOnTop(true);
                }
            } else {
                jDialogCrearUsuarios.setAlwaysOnTop(false);
                JOptionPane.showMessageDialog(this, "Nombre de usuario ya registrado", "", JOptionPane.PLAIN_MESSAGE);
                jDialogCrearUsuarios.setAlwaysOnTop(true);
            }
            usuarioDAOImpl.cerrarSession();
        } catch (SecurityException | HeadlessException e) {
            JOptionPane.showMessageDialog(this, "No se pudo realizar la solicitud", "", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (jFileChooser1.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            jTextFieldRutaPlu.setText(jFileChooser1.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jDialogCapturaPlu.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Thread thread = new Thread(new Runnable() {

            @Override
            public void run() {
                jPanel1.setVisible(true);
                jProgressBar2.setVisible(true);
                jProgressBar2.setIndeterminate(true);
                jDialogCapturaPlu.setEnabled(false);
                String ruta = jTextFieldRutaPlu.getText();
                try {
                    GestorManager.tienda = tiendaUsuario;
                    gestorManager.GestionarArchivoPlu(ruta);
                    JOptionPane.showMessageDialog(null, "Archivo cargado", "", JOptionPane.PLAIN_MESSAGE);
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "No se pudo realizar la solicitud", "", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(InterfazPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage(), "", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(InterfazPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                jDialogCapturaPlu.setEnabled(true);
                jDialogCapturaPlu.dispose();
            }
        });
        thread.start();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItemVerTiendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerTiendasActionPerformed
        PuntoVentaDAOImpl pvdaoi = dAOManager.getPuntoVentaDAOImpl();
        List<PuntoVenta> lista = pvdaoi.listar();
        pvdaoi.cerrarSession();
        DefaultTableModel model = (DefaultTableModel) jTableTienda.getModel();
        model.setNumRows(0);
        for (PuntoVenta lista1 : lista) {
            Object[] fila = new Object[6];
            fila[0] = lista1.getIdPuntoVenta();
            fila[3] = lista1.getCiudad();
            fila[2] = lista1.getDireccion();
            fila[1] = lista1.getNombre();
            fila[4] = lista1.getTelefono();
            fila[5] = lista1.getCelular();
            model.addRow(fila);
        }
        jTableTienda.setVisible(true);
        jDialogVerTiendas.setVisible(true);
        jDialogVerTiendas.setLocationRelativeTo(this);
        pvdaoi.cerrarSession();

    }//GEN-LAST:event_jMenuItemVerTiendasActionPerformed

    private void jMenuItemVerPluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerPluActionPerformed
        PluDAOImpl pvdaoi = dAOManager.getPluDAOImpl();
        List<Plu> lista = pvdaoi.listar();
        pvdaoi.cerrarSession();
        DefaultTableModel model = (DefaultTableModel) jTablePlu.getModel();
        model.setNumRows(0);
        for (Plu lista1 : lista) {
            Object[] fila = new Object[3];
            fila[0] = lista1.getIdPlu();
            fila[1] = lista1.getCodigoBarras();
            fila[2] = lista1.getNombreTextual();
            model.addRow(fila);
        }
        jTablePlu.setVisible(true);
        jDialogVerPlus.setVisible(true);
        jDialogVerPlus.setLocationRelativeTo(this);
        pvdaoi.cerrarSession();

    }//GEN-LAST:event_jMenuItemVerPluActionPerformed

    private void jMenuItemVerPreciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerPreciosActionPerformed
        PrecioDAOImpl pvdaoi = dAOManager.getPrecioDAOImpl();
        List<Precio> lista = pvdaoi.listarTodo(tiendaUsuario);
        pvdaoi.cerrarSession();
        DefaultTableModel model = (DefaultTableModel) jTablePrecio.getModel();
        model.setNumRows(0);
        for (Precio lista1 : lista) {
            Object[] fila = new Object[3];
            fila[0] = lista1.getPuntoVenta().getIdPuntoVenta();
            fila[1] = lista1.getPlu().getIdPlu();
            fila[2] = lista1.getPrecioPorKilo();
            model.addRow(fila);
        }
        jTablePrecio.setVisible(true);
        jDialogVerPrecios.setVisible(true);
        jDialogVerPrecios.setLocationRelativeTo(this);
        pvdaoi.cerrarSession();
    }//GEN-LAST:event_jMenuItemVerPreciosActionPerformed

    private void jMenuItemVerVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerVentasActionPerformed
        VentaDAOImpl pvdaoi = dAOManager.getVentaDAOImpl();
        List<Venta> lista = pvdaoi.listar();
        pvdaoi.cerrarSession();
        DefaultTableModel model = (DefaultTableModel) jTableVenta.getModel();
        model.setNumRows(0);
        for (Venta lista1 : lista) {
            Object[] fila = new Object[5];
            fila[0] = lista1.getIdVenta();
            fila[1] = lista1.getFecha();
            fila[2] = lista1.getPesoVenta();
            fila[3] = lista1.getPlu().getIdPlu();
            fila[4] = lista1.getPuntoVenta().getIdPuntoVenta();
            model.addRow(fila);
        }
        jTableVenta.setVisible(true);
        jDialogVerVentas.setVisible(true);
        jDialogVerVentas.setLocationRelativeTo(this);
        pvdaoi.cerrarSession();
    }//GEN-LAST:event_jMenuItemVerVentasActionPerformed

    private void jMenuItemRegistrarPuntoVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegistrarPuntoVentaActionPerformed
        jDialogCrearTiendas.setLocationRelativeTo(this);
        jDialogCrearTiendas.setVisible(true);
    }//GEN-LAST:event_jMenuItemRegistrarPuntoVentaActionPerformed

    private void jButtonCancelarCrearTiendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarCrearTiendaActionPerformed
        jDialogCrearTiendas.dispose();
        if (tiendaUsuario == 0) {
            hacerLogin();
        }
    }//GEN-LAST:event_jButtonCancelarCrearTiendaActionPerformed
    /**
     * *
     * Evento generado por el boton aceptar de la interfaz para crear un nuevo
     * punto de venta
     *
     * @param evt
     */
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        int idTienda = Integer.parseInt(jTextField7.getText());
        String nombre = jTextField8.getText();
        String direccion = jTextField9.getText();
        String ciudad = jTextField10.getText();
        String telefono = jTextField11.getText();
        String celular = jTextField12.getText();
        PuntoVentaDAOImpl puntoVentaDAOImpl = dAOManager.getPuntoVentaDAOImpl();
        puntoVentaDAOImpl.iniciarTransaccion();
        PuntoVenta puntoVenta = puntoVentaDAOImpl.cargar(idTienda);
        if (puntoVenta == null) {
            puntoVenta = new PuntoVenta();
            puntoVenta.setCelular(celular);
            puntoVenta.setCiudad(ciudad);
            puntoVenta.setDireccion(direccion);
            puntoVenta.setIdPuntoVenta(idTienda);
            puntoVenta.setNombre(nombre);
            puntoVenta.setTelefono(telefono);
            if (jTextField13.getText().equals("")) {
                puntoVenta.setDirectorioDefecto("C:\\");
            } else {
                puntoVenta.setDirectorioDefecto(jTextField13.getText());
            }
            puntoVentaDAOImpl.guardar(puntoVenta);
            puntoVentaDAOImpl.commit();
            puntoVentaDAOImpl.cerrarSession();
            JOptionPane.showMessageDialog(this, "Punto de venta registrado exitosamente", "", JOptionPane.INFORMATION_MESSAGE);
            jDialogCrearTiendas.dispose();
            if (tiendaUsuario == 0) {
                hacerLogin();
            }
            //JOptionPane.showMessageDialog(this, "Base de datos: T" + puntoVenta.getIdPuntoVenta() + " creada exitosamente", "", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Esta tienda ya se encuentra registrada", "", JOptionPane.WARNING_MESSAGE);
            jDialogCrearTiendas.dispose();
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        PuntoVentaDAOImpl pvdaoi = dAOManager.getPuntoVentaDAOImpl();
        pvdaoi.iniciarTransaccion();
        DefaultTableModel model = (DefaultTableModel) jTableTienda.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            PuntoVenta puntoVenta = new PuntoVenta();
            puntoVenta.setIdPuntoVenta((int) model.getValueAt(i, 0));
            puntoVenta.setNombre((String) model.getValueAt(i, 1));
            puntoVenta.setDireccion((String) model.getValueAt(i, 2));
            puntoVenta.setCiudad((String) model.getValueAt(i, 3));
            puntoVenta.setTelefono((String) model.getValueAt(i, 4));
            puntoVenta.setCelular((String) model.getValueAt(i, 5));
            pvdaoi.actualizar(puntoVenta);
        }
        JOptionPane.showMessageDialog(this, "Puntos de ventas actualizados", "", JOptionPane.INFORMATION_MESSAGE);
        pvdaoi.commit();
        pvdaoi.cerrarSession();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        PrecioDAOImpl pvdaoi = dAOManager.getPrecioDAOImpl();
        pvdaoi.iniciarTransaccion();
        DefaultTableModel model = (DefaultTableModel) jTablePrecio.getModel();
        for (int i = 0; i < model.getRowCount(); i++) {
            int idPlu = (int) model.getValueAt(i, 1);
            int idTienda = (int) model.getValueAt(i, 0);
            Precio precio = pvdaoi.cargarPrecioPorPluYTienda(idPlu, idTienda);
            precio.setPrecioPorKilo((int) model.getValueAt(i, 2));
            pvdaoi.actualizar(precio);
        }
        JOptionPane.showMessageDialog(this, "Precios actualizados", "", JOptionPane.INFORMATION_MESSAGE);
        pvdaoi.commit();
        pvdaoi.cerrarSession();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if (jFileChooser2.showOpenDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            jTextField13.setText(jFileChooser2.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jMenuItemVerMovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVerMovimientoActionPerformed
        MovimientoDAOImpl pvdaoi = dAOManager.getMovimientoDAOImpl();
        List<Movimiento> lista = pvdaoi.listar();
        pvdaoi.cerrarSession();
        DefaultTableModel model = (DefaultTableModel) jTableMovimiento.getModel();
        model.setNumRows(0);
        for (Movimiento lista1 : lista) {
            Object[] fila = new Object[9];
            fila[0] = lista1.getIdMovimiento();
            fila[1] = lista1.getPlu();
            fila[2] = lista1.getPrecioKilo();
            fila[3] = lista1.getPesoVenta();
            fila[4] = lista1.getPrecioVenta();
            fila[5] = lista1.getFecha();
            fila[6] = lista1.getHora();
            fila[7] = lista1.getEscala();
            fila[8] = lista1.getNombre().trim();
            model.addRow(fila);
        }
        jTableMovimiento.setVisible(true);
        jDialogVerMovimiento.setVisible(true);
        jDialogVerMovimiento.setLocationRelativeTo(this);
    }//GEN-LAST:event_jMenuItemVerMovimientoActionPerformed

    private void jMenuItemReporteEscalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReporteEscalaActionPerformed
        Thread thread = new Thread(new Runnable() {

            @Override
            public void run() {
                try {
                    jDialogCargaCrearReporte.setLocationRelativeTo(null);
                    jDialogCargaCrearReporte.setVisible(true);
                    File f = new File("plantillasReportes\\report3.jasper");
                    JasperReport reporte = (JasperReport) JRLoader.loadObject(f);
                    JasperPrint jasperPrint = JasperFillManager.fillReport(reporte, null, dAOManager.getMovimientoDAOImpl().getCurrentSession().connection());

                    jDialogCargaCrearReporte.dispose();
                    JOptionPane.showMessageDialog(null, "Reporte generado exitosamente", "", JOptionPane.INFORMATION_MESSAGE);

                    JasperViewer visor = new JasperViewer(jasperPrint, false);
                    visor.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                    visor.setVisible(true);
                } catch (JRException ex) {
                    JOptionPane.showMessageDialog(null, "No ha sido posible generar el reporte", "", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        });
        thread.start();

    }//GEN-LAST:event_jMenuItemReporteEscalaActionPerformed

    private void jMenuItemReportePluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReportePluActionPerformed
        Thread thread = new Thread(new Runnable() {

            @Override
            public void run() {
                try {
                    jDialogCargaCrearReporte.setLocationRelativeTo(null);
                    jDialogCargaCrearReporte.setVisible(true);
                    File f = new File("plantillasReportes\\report4.jasper");
                    JasperReport reporte = (JasperReport) JRLoader.loadObject(f);
                    JasperPrint jasperPrint = JasperFillManager.fillReport(reporte, null, dAOManager.getMovimientoDAOImpl().getCurrentSession().connection());

                    jDialogCargaCrearReporte.dispose();
                    JOptionPane.showMessageDialog(null, "Reporte generado exitosamente", "", JOptionPane.INFORMATION_MESSAGE);

                    JasperViewer visor = new JasperViewer(jasperPrint, false);
                    visor.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                    visor.setVisible(true);
                } catch (JRException ex) {
                    JOptionPane.showMessageDialog(null, "No ha sido posible generar el reporte", "", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        });
        thread.start();
    }//GEN-LAST:event_jMenuItemReportePluActionPerformed

    private void jMenuItemReporteFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReporteFechaActionPerformed
        Thread thread = new Thread(new Runnable() {

            @Override
            public void run() {
                try {
                    jDialogCargaCrearReporte.setLocationRelativeTo(null);
                    jDialogCargaCrearReporte.setVisible(true);
                    // TODO add your handling code here:
                    File f = new File("plantillasReportes\\report2.jasper");
                    JasperReport reporte = (JasperReport) JRLoader.loadObject(f);
                    JasperPrint jasperPrint = JasperFillManager.fillReport(reporte, null, dAOManager.getMovimientoDAOImpl().getCurrentSession().connection());

                    jDialogCargaCrearReporte.dispose();
                    JOptionPane.showMessageDialog(null, "Reporte generado exitosamente", "", JOptionPane.INFORMATION_MESSAGE);

                    JasperViewer visor = new JasperViewer(jasperPrint, false);
                    visor.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
                    visor.setVisible(true);
                } catch (JRException ex) {
                    JOptionPane.showMessageDialog(null, "No ha sido posible generar el reporte", "", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        });
        thread.start();
    }//GEN-LAST:event_jMenuItemReporteFechaActionPerformed

    /**
     * *
     * Evento que genera la consolidación de los datos en el punto de venta que
     * tiene la sesión activa
     *
     * @param evt
     */
    private void jMenuItemConsolidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConsolidarActionPerformed
        System.out.println("Brinca");
        if (tiendaUsuario > 50 && tiendaUsuario < 99) {
            System.out.println("Comenzó");
            dAOManager.getMovimientoDAOImpl().iniciarTransaccion();

            List<Movimiento> movimientos = dAOManager.getMovimientoDAOImpl().listar();
            List<Plu> plus = dAOManager.getPluDAOImpl().listar();
            List<Precio> precios = dAOManager.getPrecioDAOImpl().listar();
            List<Venta> ventas = dAOManager.getVentaDAOImpl().listar();


            dAOManager.getMovimientoDAOImpl().iniciarTransaccion();
            for (Movimiento m : movimientos) {
                if (dAOManager.getMovimientoDAOImpl().cargar(m.getIdMovimiento()) == null) {
                    dAOManager.getMovimientoDAOImpl().guardar(m);
                }
            }
            dAOManager.getMovimientoDAOImpl().commit();

            dAOManager.getPluDAOImpl().iniciarTransaccion();
            for (Plu p : plus) {
                if (dAOManager.getPluDAOImpl().cargar(p.getIdPlu()) == null) {
                    dAOManager.getPluDAOImpl().guardar(p);
                }
            }
            dAOManager.getPluDAOImpl().commit();

            dAOManager.getPrecioDAOImpl().iniciarTransaccion();
            for (Precio p : precios) {
                if (dAOManager.getPrecioDAOImpl().cargarPrecioPorPluYTienda(p.getPlu().getIdPlu(), p.getPuntoVenta().getIdPuntoVenta()) == null) {
                    dAOManager.getPrecioDAOImpl().guardar(p);
                }
            }
            dAOManager.getPrecioDAOImpl().commit();

            dAOManager.getVentaDAOImpl().iniciarTransaccion();
            for (Venta v : ventas) {
                if (dAOManager.getVentaDAOImpl().cargar(v.getIdVenta()) == null) {
                    dAOManager.getVentaDAOImpl().guardar(v);
                }
            }
            dAOManager.getVentaDAOImpl().commit();
            dAOManager.getVentaDAOImpl().cerrarSession();

            System.out.println("Termino");
        }
        System.out.println("Salta");
    }//GEN-LAST:event_jMenuItemConsolidarActionPerformed

    /**
     * *
     * Evento para consolidar toda la información en la base de datos T99
     *
     * @param evt
     */
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        if (tiendaUsuario == 99) {
            dAOManager.getMovimientoDAOImpl().iniciarTransaccion();

            List<Integer> tiendasBD = dAOManager.getPuntoVentaDAOImpl().listaId();

            for (int tbd : tiendasBD) {

                List<Movimiento> movimientos = dAOManager.getMovimientoDAOImpl().listar();
                List<Plu> plus = dAOManager.getPluDAOImpl().listar();
                List<Precio> precios = dAOManager.getPrecioDAOImpl().listar();
                List<Venta> ventas = dAOManager.getVentaDAOImpl().listar();


                dAOManager.getMovimientoDAOImpl().iniciarTransaccion();
                for (Movimiento m : movimientos) {
                    if (dAOManager.getMovimientoDAOImpl().cargar(m.getIdMovimiento()) == null) {
                        dAOManager.getMovimientoDAOImpl().guardar(m);
                    }
                }
                dAOManager.getMovimientoDAOImpl().commit();

                dAOManager.getPluDAOImpl().iniciarTransaccion();
                for (Plu p : plus) {
                    if (dAOManager.getPluDAOImpl().cargar(p.getIdPlu()) == null) {
                        dAOManager.getPluDAOImpl().guardar(p);
                    }
                }
                dAOManager.getPluDAOImpl().commit();

                dAOManager.getPrecioDAOImpl().iniciarTransaccion();
                for (Precio p : precios) {
                    if (dAOManager.getPrecioDAOImpl().cargarPrecioPorPluYTienda(p.getPlu().getIdPlu(), p.getPuntoVenta().getIdPuntoVenta()) == null) {
                        dAOManager.getPrecioDAOImpl().guardar(p);
                    }
                }
                dAOManager.getPrecioDAOImpl().commit();

                dAOManager.getVentaDAOImpl().iniciarTransaccion();
                for (Venta v : ventas) {
                    if (dAOManager.getVentaDAOImpl().cargar(v.getIdVenta()) == null) {
                        dAOManager.getVentaDAOImpl().guardar(v);
                    }
                }
                dAOManager.getVentaDAOImpl().commit();
            }
            dAOManager.getVentaDAOImpl().cerrarSession();

        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menuSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalir2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuSalir2ActionPerformed

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
        this.ventanaInicio.setVisible(false);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setVisible(true);
        this.setEnabled(true);

        List<Integer> tiendas = dAOManager.getPuntoVentaDAOImpl().listaId();
        if (tiendas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay tiendas registradas", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            jDialogCrearUsuarios.setVisible(true);
            jDialogCrearUsuarios.setLocationRelativeTo(this);
        }
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jComboBoxUsuariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxUsuariosItemStateChanged
        if (jComboBoxUsuarios.getSelectedIndex() < 0) {
            jTextField1.setText("");
        } else {
            jTextField1.setText(jComboBoxUsuarios.getSelectedItem().toString());
        }
    }//GEN-LAST:event_jComboBoxUsuariosItemStateChanged

    /**
     * *
     * Evento generado por el boton aceptar de la interfaz de loggin Usado para
     * establecer que usuario se ha logueado a la aplicación
     *
     * @param evt
     */
    private void btnAcpetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcpetarActionPerformed
        if (!jTextField1.getText().equals("") && !jPasswordField1.getText().equals("")) {
            //Conexión por medio del superUsuario local de la aplicación
            char[] c = "0123456789aÑ".toCharArray();
            if (jTextField1.getText().equals("Superusuario") && Arrays.equals(jPasswordField1.getPassword(), c)) {
                this.ventanaInicio.setVisible(false);
                this.setExtendedState(MAXIMIZED_BOTH);
                this.setVisible(true);
                this.setEnabled(true);
                InterfazPrincipal.tipoUsuario = "Superusuario";
            } else {
                //Usuarios de DB
                try {
                    UsuarioDAOImpl usuarioDAOImpl = dAOManager.getUsuarioDAOImpl();
                    Usuario usuario = usuarioDAOImpl.buscarPorNombreUsuarioYContrasena(jTextField1.getText(), jPasswordField1.getText());
                    if (usuario != null) {
                        this.ventanaInicio.setVisible(false);
                        this.setExtendedState(MAXIMIZED_BOTH);
                        this.setVisible(true);
                        this.setEnabled(true);
                        InterfazPrincipal.tipoUsuario = usuario.getTipoUsuario();
                    } else {
                        ventanaInicio.setAlwaysOnTop(false);
                        JOptionPane.showMessageDialog(this, "Información de logueo incorrecta", "", JOptionPane.PLAIN_MESSAGE);
                        ventanaInicio.setAlwaysOnTop(true);
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "No se pudo realizar la solicitud", "", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            jLabelTienda.setText((tiendaUsuario < 0 || tiendaUsuario > 99) ? " No tiene punto de venta asociado " : "El punto de venta asociado es: " + tiendaUsuario);
            jLabelTipoUsuario.setText("El tipo de usuario que actualmente esta operando es: " + tipoUsuario);
            jLabelNombreTienda.setText("Tienda actual: "+nombreTienda);
            
            jPanelInformacionUsuario.setVisible(true);
        } else {
            ventanaInicio.setAlwaysOnTop(false);
            JOptionPane.showMessageDialog(this, "Campos vacios, por favor ingrese información de logueo", "", JOptionPane.PLAIN_MESSAGE);
            ventanaInicio.setAlwaysOnTop(true);
        }
    }//GEN-LAST:event_btnAcpetarActionPerformed

    private void hacerLogin() {
        jTextField1.setText("");
        jPasswordField1.setText("");
        this.setEnabled(false);
        llenarComboBoxUsuario();
        this.ventanaInicio.setVisible(true);
        this.ventanaInicio.setLocationRelativeTo(this);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazPrincipal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            Process process = Runtime.getRuntime().exec("net start");
            BufferedReader br = new BufferedReader(new InputStreamReader(process.getInputStream()));
            String s;
            while ((s = br.readLine()) != null) {
                s = s.trim();
                if (!s.equals("")) {
                    if (s.contains("SQL Server")) {
                        stateConnection++;
                    }
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(InterfazPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    HibernateDAOImpl hdaoi = new HibernateDAOImpl(Object.class);
                    if (stateConnection < 1) {
                        throw new Exception();
                    }
                    if (hdaoi.getCurrentSession().connection().isClosed()) {
                    }
                    InterfazPrincipal escritorio = new InterfazPrincipal();
                    escritorio.setExtendedState(MAXIMIZED_BOTH);
                    escritorio.setVisible(true);
                    escritorio.ventanaInicio.setLocationRelativeTo(escritorio);
                    escritorio.ventanaInicio.setVisible(true);
                    escritorio.jPanelInformacionUsuario.setVisible(false);
                    escritorio.setEnabled(false);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "No se pudo establecer la conexión requerida, revisa la configuración del sistema : " + stateConnection, "\n Comunicate con el encargado", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcpetar;
    private javax.swing.JMenuItem itemAyuda;
    private javax.swing.JMenuItem itemAyuda2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonCancelarCrearTienda;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBoxUsuarios;
    private javax.swing.JDialog jDialogCapturaPlu;
    private javax.swing.JDialog jDialogCargaCrearReporte;
    private javax.swing.JDialog jDialogCrearTiendas;
    private javax.swing.JDialog jDialogCrearUsuarios;
    private javax.swing.JDialog jDialogVerMovimiento;
    private javax.swing.JDialog jDialogVerPlus;
    private javax.swing.JDialog jDialogVerPrecios;
    private javax.swing.JDialog jDialogVerTiendas;
    private javax.swing.JDialog jDialogVerVentas;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelNombreTienda;
    private javax.swing.JLabel jLabelTienda;
    private javax.swing.JLabel jLabelTipoUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenu jMenuConsolidar;
    private javax.swing.JMenu jMenuImportar;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemCapturarPlu;
    private javax.swing.JMenuItem jMenuItemConsolidar;
    private javax.swing.JMenuItem jMenuItemRegistrarPuntoVenta;
    private javax.swing.JMenuItem jMenuItemReporteEscala;
    private javax.swing.JMenuItem jMenuItemReporteFecha;
    private javax.swing.JMenuItem jMenuItemReportePlu;
    private javax.swing.JMenuItem jMenuItemVerMovimiento;
    private javax.swing.JMenuItem jMenuItemVerPlu;
    private javax.swing.JMenuItem jMenuItemVerPrecios;
    private javax.swing.JMenuItem jMenuItemVerTiendas;
    private javax.swing.JMenuItem jMenuItemVerVentas;
    private javax.swing.JMenu jMenuReporte;
    private javax.swing.JMenu jMenuVista;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelInformacionUsuario;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTableMovimiento;
    private javax.swing.JTable jTablePlu;
    private javax.swing.JTable jTablePrecio;
    private javax.swing.JTable jTableTienda;
    private javax.swing.JTable jTableVenta;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldRutaPlu;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuArchivo2;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenu menuAyuda2;
    private javax.swing.JMenuItem menuCrearUsuario;
    private javax.swing.JMenu menuHerramientas;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenuItem menuSalir2;
    private javax.swing.JMenuItem menuSesion;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JFrame ventanaInicio;
    // End of variables declaration//GEN-END:variables

}
